project:
  output-dir: ./docs
  type: website
  render:
    - "*.qmd"
    - "!archive/"
  post-render:
    - cp googleb16326ba55692535.html docs/googleb16326ba55692535.html
  
website:
  page-navigation: true
  navbar:
    logo: "./images/logo_without_bakground_small.png"
    logo-alt: "ECOFLOR 2026"
    background: rgb(255,244,224)
    left:
      - href: index.qmd#about
        text: "About" 
      - href: index.qmd#registration
        text: "Registration"     
      - href: index.qmd#programme
        text: "Programme"
      - href: index.qmd#venue
        text: "Venue" 
      - href: index.qmd#organisation
        text: "Organisation committee"  
      - href: index.qmd#acknowledgements
        text: "Acknowledgements"  
        
      - href: index.qmd#contact
        text: "Contact"
    right:
      - icon: github
        href: https://github.com/Pollination-Ecology-Group/ECOFLOR2026
      - icon: discord 
        href: https://discord.gg/Ser2GRXgns  
      - icon: whatsapp
        href: https://chat.whatsapp.com/KCycNVzqLEm1orgBQGjrQ2?mode=ems_copy_t      
  page-footer: 
    left: "Made by Jakub Å tenc" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: discord 
        href: https://discord.gg/Ser2GRXgns
      - icon: instagram
        href: https://www.instagram.com/ecoflor2026/
      - icon: whatsapp
        href: https://chat.whatsapp.com/KCycNVzqLEm1orgBQGjrQ2?mode=ems_copy_t
  announcement:
    icon: info-circle
    dismissable: true
    content: "Registration is now closed! Stay tuned for updates on the programme."
    type: light
    position: below-navbar
  back-to-top-navigation: true
  cookie-consent: true

format:
  html:
    fontsize: 1.15rem
    monofont: Fira Code
    highlight-style: arrow
    css: [custom_theme.scss]
    toc: true
    smooth-scroll: true
    code-overflow: scroll
    linkcolor: rgb(97,30,30)
    background: rgb(255,244,224)
    theme: cosmo